services:
  - type: web
    name: coze-review-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: COZE_API_KEY
        sync: false
    disk:
      name: uploads
      mountPath: uploads
      sizeGB: 1
